### ISSUE TITLE
Review?

### ISSUE THREAD

**Issue by joelmukuthu** [unexpectedjs/unexpected-knex#1]
@unexpectedjs/owners could I trouble you guys for a review? :)

**Comment by papandreou** [comment]
Sure! It looks really cool, but I don't know much about knex itself. Could we take a look at it together at work when we have some time?

**Comment by sunesimonsen** [comment]
Sorry did you still want help? I don't know Knex, so I don't know if I
would be of any help.

**Comment by joelmukuthu** [comment]
No, that's okay :) I was just cleaning up and this issue wasn't relevant anymore.

**Comment by sunesimonsen** [comment]
Sorry for never responding. So much to do, so little time.

**Comment by joelmukuthu** [comment]
I can relate. We actually talked about this some time back at a bar and that was a review in itself :grinning:. If I get some time I would like to marry this with chance-generators though. Such that the plugin would look at a migration and come up with some random data to run the test with. I think MongoDb did something like that with some fuzzy testing. Though at that point it's not really an unexpected plugin.
